import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, LoaderCircle, Plus, Search, Trash2 } from 'lucide-react';
import { fetchMembers } from '../../admin/services/membersApi';
import type { Member } from '../../admin/pages/MembershipManagement';

export const MAX_LOAN_PER_HECTARE = 50000;
export const DEFAULT_INTEREST_RATE = 2.5;

export type LoanApplicationPayload = {
  memberId: number;
  loanType: string; amount: string; term: string; purpose: string; monthlyIncome: string;
  borrowerEmail: string; borrowerPhone: string; borrowerAddress: string; borrowerAge: string;
  borrowerGender: string; borrowerCivilStatus: string; borrowerOccupation: string; yearsFarming: string;
  farmLocation: string; barangay: string; municipality: string; province: string; farmArea: string;
  cropsPlanted: string; cropSeason: string; irrigationType: string; irrigationOther: string; loanMode: string;
  inKindItems: Array<{ item: string; description: string; quantity: string; unit: string; unitPrice: string }>;
  coMakerName: string; coMakerAddress: string; coMakerContact: string; coMakerRelationship: string;
  collateralType: string; collateralDetails: string;
};

type Props = {
  initialMember?: Member | null;
  allowMemberLookup?: boolean;
  submitLabel: string;
  onSubmit: (payload: LoanApplicationPayload) => Promise<void>;
  onCancel: () => void;
};

const blank = (): LoanApplicationPayload => ({
  memberId: 0, loanType: 'agricultural', amount: '', term: '12', purpose: '', monthlyIncome: '',
  borrowerEmail: '', borrowerPhone: '', borrowerAddress: '', borrowerAge: '', borrowerGender: '', borrowerCivilStatus: '', borrowerOccupation: '', yearsFarming: '',
  farmLocation: '', barangay: '', municipality: '', province: '', farmArea: '', cropsPlanted: '', cropSeason: '', irrigationType: 'rainfed', irrigationOther: '', loanMode: 'cash',
  inKindItems: [], coMakerName: '', coMakerAddress: '', coMakerContact: '', coMakerRelationship: '', collateralType: '', collateralDetails: '',
});
const money = (value: number) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP' }).format(value || 0);
const ageFromBirthday = (value: string) => { if (!value) return ''; const birth = new Date(value); if (Number.isNaN(birth.getTime())) return ''; const today = new Date(); let age = today.getFullYear() - birth.getFullYear(); if (today.getMonth() < birth.getMonth() || (today.getMonth() === birth.getMonth() && today.getDate() < birth.getDate())) age--; return age >= 0 ? String(age) : ''; };

function memberToForm(member: Member): Partial<LoanApplicationPayload> {
  return {
    memberId: member.id, borrowerEmail: member.email || '', borrowerPhone: member.phone || '', borrowerAddress: member.address || '',
    borrowerAge: ageFromBirthday(member.profile?.birthday || ''), borrowerGender: member.profile?.gender || '', borrowerCivilStatus: member.profile?.civilStatus || '',
    borrowerOccupation: member.profile?.livelihood || '', farmArea: member.profile?.farmArea || '', barangay: member.profile?.barangay || '', municipality: member.profile?.municipality || '', province: member.profile?.province || '',
  };
}

const Field = ({ label, required, children, hint }: { label: string; required?: boolean; children: React.ReactNode; hint?: string }) => <label className="block text-sm font-medium text-slate-700"><span>{label}{required && <span className="text-red-600"> *</span>}</span>{hint && <span className="ml-2 text-xs font-normal text-slate-500">{hint}</span>}<div className="mt-1.5">{children}</div></label>;
const input = 'min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-slate-900 outline-none transition focus:border-green-600 focus:ring-2 focus:ring-green-100 disabled:bg-slate-100';

export function LoanApplicationWizard({ initialMember = null, allowMemberLookup = false, submitLabel, onSubmit, onCancel }: Props) {
  const [form, setForm] = useState<LoanApplicationPayload>(() => initialMember ? { ...blank(), ...memberToForm(initialMember) } : blank());
  const [selectedMember, setSelectedMember] = useState<Member | null>(initialMember);
  const [memberSearch, setMemberSearch] = useState(initialMember?.memberId || '');
  const [matches, setMatches] = useState<Member[]>([]);
  const [searching, setSearching] = useState(false);
  const [lookupMessage, setLookupMessage] = useState('');
  const [step, setStep] = useState(1);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [confirming, setConfirming] = useState(false);

  const area = Number(form.farmArea) || 0;
  const requested = Number(form.amount) || 0;
  const maximum = area * MAX_LOAN_PER_HECTARE;
  const interest = requested * DEFAULT_INTEREST_RATE / 100;
  const total = requested + interest;
  const monthly = total / (Number(form.term) || 1);
  const inKindTotal = form.inKindItems.reduce((sum, item) => sum + (Number(item.quantity) || 0) * (Number(item.unitPrice) || 0), 0);
  const steps = ['Borrower', 'Farm', 'Loan', 'Farm inputs', 'Co-maker', 'Collateral', 'Review'];
  const needsInputs = ['in-kind', 'combination'].includes(form.loanMode);

  useEffect(() => {
    if (!allowMemberLookup || selectedMember || memberSearch.trim().length < 2) { setMatches([]); return; }
    const timer = window.setTimeout(async () => {
      setSearching(true); setLookupMessage('');
      try { const response = await fetchMembers(memberSearch, 8); setMatches(response.data); setLookupMessage(response.data.length ? '' : 'Member not found. Check the Member / Associate ID or search by name.'); }
      catch { setMatches([]); setLookupMessage('Member search is currently unavailable.'); }
      finally { setSearching(false); }
    }, 250);
    return () => window.clearTimeout(timer);
  }, [allowMemberLookup, memberSearch, selectedMember]);

  const update = (key: keyof LoanApplicationPayload, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const selectMember = (member: Member) => { setSelectedMember(member); setMemberSearch(member.memberId); setForm((current) => ({ ...current, ...memberToForm(member) })); setMatches([]); setLookupMessage('Member record auto-filled. Changes below apply only to this application.'); };
  const clearMember = () => { setSelectedMember(null); setMemberSearch(''); setForm(blank()); setLookupMessage(''); };
  const addItem = () => setForm((current) => ({ ...current, inKindItems: [...current.inKindItems, { item: '', description: '', quantity: '', unit: '', unitPrice: '' }] }));
  const updateItem = (index: number, key: 'item' | 'description' | 'quantity' | 'unit' | 'unitPrice', value: string) => setForm((current) => ({ ...current, inKindItems: current.inKindItems.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) }));
  const removeItem = (index: number) => setForm((current) => ({ ...current, inKindItems: current.inKindItems.filter((_, itemIndex) => itemIndex !== index) }));

  const stepValid = useMemo(() => {
    if (step === 1) return !!(form.memberId && form.borrowerEmail && form.borrowerPhone && form.borrowerAddress);
    if (step === 2) return area > 0 && !!(form.cropsPlanted && form.cropSeason && form.barangay && form.municipality && form.province) && (form.irrigationType !== 'other' || !!form.irrigationOther);
    if (step === 3) return !!(form.loanType && form.purpose && form.loanMode && Number.isInteger(Number(form.term)) && Number(form.term) > 0 && requested > 0 && requested <= maximum);
    if (step === 4) return !needsInputs || (form.inKindItems.length > 0 && form.inKindItems.every((item) => item.item && item.quantity && Number(item.quantity) > 0 && item.unit && item.unitPrice && Number(item.unitPrice) > 0));
    return true;
  }, [step, form, area, maximum, requested, needsInputs]);
  const next = () => { if (!stepValid) { setError(step === 3 && requested > maximum ? `Requested loan amount exceeds the maximum eligible amount of ${money(maximum)} for ${area} hectares.` : 'Complete the required fields with valid values before continuing.'); return; } setError(''); setStep((current) => Math.min(7, current + 1)); };
  const submit = async () => { if (!stepValid) { setError('Please correct the application before submitting.'); return; } setSaving(true); setError(''); try { await onSubmit(form); } catch (submitError) { setConfirming(false); setError(submitError instanceof Error ? submitError.message : 'Unable to submit the application.'); } finally { setSaving(false); } };

  const calculationPanel = <aside className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><h3 className="font-bold">Loan eligibility</h3><dl className="mt-3 space-y-2"><div className="flex justify-between gap-4"><dt>Farm area</dt><dd className="font-semibold">{area.toFixed(2)} ha</dd></div><div className="flex justify-between gap-4"><dt>Maximum per hectare</dt><dd className="font-semibold">{money(MAX_LOAN_PER_HECTARE)}</dd></div><div className="flex justify-between gap-4 border-t border-emerald-200 pt-2"><dt>Maximum eligible</dt><dd className="font-bold">{money(maximum)}</dd></div><div className="flex justify-between gap-4"><dt>Requested amount</dt><dd className={requested > maximum ? 'font-bold text-red-700' : 'font-semibold'}>{money(requested)}</dd></div><div className="flex justify-between gap-4"><dt>Interest rate</dt><dd className="font-semibold">{DEFAULT_INTEREST_RATE}% flat per term</dd></div><div className="flex justify-between gap-4"><dt>Estimated interest</dt><dd className="font-semibold">{money(interest)}</dd></div><div className="flex justify-between gap-4 border-t border-emerald-200 pt-2"><dt>Total repayment</dt><dd className="font-bold">{money(total)}</dd></div><div className="flex justify-between gap-4"><dt>Est. monthly payment</dt><dd className="font-semibold">{money(monthly)}</dd></div></dl><p className="mt-3 text-xs text-emerald-800">Final values are recalculated by ACIFAC’s backend before saving.</p></aside>;

  return <div className="flex min-h-0 flex-1 flex-col"><div className="border-b border-slate-200 px-4 py-4 sm:px-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900 sm:text-xl">Agricultural Loan Application</h2><p className="text-sm text-slate-500">Step {step} of 7 — {steps[step - 1]}</p></div><button type="button" onClick={onCancel} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Close application">×</button></div><ol className="mt-4 grid grid-cols-7 gap-1" aria-label="Application progress">{steps.map((label, index) => <li key={label}><div className={`h-2 rounded-full ${index + 1 <= step ? 'bg-green-600' : 'bg-slate-200'}`} /><span className="mt-1 hidden text-[10px] text-slate-500 lg:block">{label}</span></li>)}</ol></div>
    <div className="flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-5xl">{error && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}
      {step === 1 && <div className="space-y-5"><div className="rounded-2xl border border-green-200 bg-green-50 p-4"><Field label="Member / Associate ID" required hint="Search by ID first; name also works"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-5 w-5 text-slate-400" /><input className={`${input} pl-10`} value={memberSearch} disabled={!allowMemberLookup || !!selectedMember} onChange={(event) => setMemberSearch(event.target.value)} placeholder="ACIFAC-2026-001 or member name" />{selectedMember && allowMemberLookup && <button type="button" onClick={clearMember} className="absolute right-2 top-2 rounded-lg px-2 py-1 text-xs font-semibold text-green-700 hover:bg-green-100">Change</button>}</div></Field>{searching && <p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><LoaderCircle className="h-4 w-4 animate-spin" /> Finding members…</p>}{matches.length > 0 && <div className="mt-2 max-h-48 overflow-auto rounded-xl border border-slate-200 bg-white">{matches.map((member) => <button type="button" key={member.id} onClick={() => selectMember(member)} className="block w-full border-b border-slate-100 px-3 py-3 text-left last:border-0 hover:bg-slate-50"><span className="block font-semibold text-slate-900">{member.name}</span><span className="text-xs text-slate-500">{member.memberId} · {member.phone || 'No contact number'}</span></button>)}</div>}{lookupMessage && <p className="mt-2 text-sm text-slate-600">{lookupMessage}</p>}</div>
        {!selectedMember && <p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Select a valid active member before continuing. No new member record will be created by this form.</p>}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Full name"><input className={input} value={selectedMember?.name || ''} readOnly placeholder="Auto-filled from member record" /></Field><Field label="Occupation"><input className={input} value={form.borrowerOccupation} onChange={(e) => update('borrowerOccupation', e.target.value)} /></Field><Field label="Years of farming"><input className={input} type="number" min="0" max="100" step="0.01" value={form.yearsFarming} onChange={(e) => update('yearsFarming', e.target.value)} /></Field><Field label="Age"><input className={input} type="number" min="0" max="120" value={form.borrowerAge} onChange={(e) => update('borrowerAge', e.target.value)} /></Field><Field label="Civil status"><input className={input} value={form.borrowerCivilStatus} onChange={(e) => update('borrowerCivilStatus', e.target.value)} /></Field><Field label="Sex / Gender"><input className={input} value={form.borrowerGender} onChange={(e) => update('borrowerGender', e.target.value)} /></Field><Field label="Contact number" required><input className={input} value={form.borrowerPhone} onChange={(e) => update('borrowerPhone', e.target.value)} /></Field><Field label="Email" required><input className={input} type="email" value={form.borrowerEmail} onChange={(e) => update('borrowerEmail', e.target.value)} /></Field><Field label="Address" required><input className={input} value={form.borrowerAddress} onChange={(e) => update('borrowerAddress', e.target.value)} /></Field></div><p className="text-xs text-slate-500">Auto-filled member data is a snapshot for this application. Editing it here does not change the permanent member record.</p></div>}
      {step === 2 && <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="grid content-start gap-4 sm:grid-cols-2"><Field label="Farm location / Sitio"><input className={input} value={form.farmLocation} onChange={(e) => update('farmLocation', e.target.value)} /></Field><Field label="Barangay" required><input className={input} value={form.barangay} onChange={(e) => update('barangay', e.target.value)} /></Field><Field label="Municipality" required><input className={input} value={form.municipality} onChange={(e) => update('municipality', e.target.value)} /></Field><Field label="Province" required><input className={input} value={form.province} onChange={(e) => update('province', e.target.value)} /></Field><Field label="Total farm area (hectares)" required><input className={input} type="number" min="0.01" max="10000" step="0.01" value={form.farmArea} onChange={(e) => update('farmArea', e.target.value)} /></Field><Field label="Crops planted" required><input className={input} value={form.cropsPlanted} onChange={(e) => update('cropsPlanted', e.target.value)} placeholder="e.g., rice, corn" /></Field><Field label="Crop season / year" required><input className={input} value={form.cropSeason} onChange={(e) => update('cropSeason', e.target.value)} placeholder="e.g., Wet season 2026" /></Field><Field label="Irrigation type" required><select className={input} value={form.irrigationType} onChange={(e) => update('irrigationType', e.target.value)}><option value="rainfed">Rainfed</option><option value="irrigated">Irrigated</option><option value="other">Other</option></select></Field>{form.irrigationType === 'other' && <Field label="Other irrigation details" required><input className={input} value={form.irrigationOther} onChange={(e) => update('irrigationOther', e.target.value)} /></Field>}</div>{calculationPanel}</div>}
      {step === 3 && <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="grid content-start gap-4 sm:grid-cols-2"><Field label="Loan type" required><select className={input} value={form.loanType} onChange={(e) => update('loanType', e.target.value)}><option value="agricultural">Agricultural</option><option value="personal">Personal</option><option value="emergency">Emergency</option></select></Field><Field label="Loan mode" required><select className={input} value={form.loanMode} onChange={(e) => update('loanMode', e.target.value)}><option value="cash">Cash</option><option value="in-kind">In-Kind</option><option value="combination">Combination</option></select></Field><Field label="Loan purpose" required><textarea className={input} value={form.purpose} onChange={(e) => update('purpose', e.target.value)} rows={3} /></Field><Field label="Requested loan amount" required><input className={input} type="number" min="0.01" max={maximum || undefined} step="0.01" value={form.amount} onChange={(e) => update('amount', e.target.value)} /></Field><Field label="Loan term (months)" required><select className={input} value={form.term} onChange={(e) => update('term', e.target.value)}>{[6, 12, 18, 24, 36, 48, 60].map((term) => <option key={term} value={term}>{term} months</option>)}</select></Field><Field label="Monthly income"><input className={input} type="number" min="0" step="0.01" value={form.monthlyIncome} onChange={(e) => update('monthlyIncome', e.target.value)} /></Field>{requested > maximum && <p className="sm:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700">Requested loan amount exceeds the maximum eligible amount of {money(maximum)} for {area} hectares.</p>}</div>{calculationPanel}</div>}
      {step === 4 && <div className="space-y-4"><div><h3 className="font-bold text-slate-900">In-kind loan details / farm inputs</h3><p className="text-sm text-slate-500">{needsInputs ? 'Add every input requested. The total is calculated from quantity × unit price.' : 'This cash application has no in-kind items. You may continue.'}</p></div>{needsInputs && <><div className="space-y-3">{form.inKindItems.map((item, index) => <div key={index} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Field label="Item" required><select className={input} value={item.item} onChange={(e) => updateItem(index, 'item', e.target.value)}><option value="">Select input</option>{['Fertilizer', 'Pesticides', 'Herbicides', 'Insecticides', 'Seeds', 'Plant Chemicals for Spray', 'Other Farm Inputs'].map((name) => <option key={name}>{name}</option>)}</select></Field><Field label="Description"><input className={input} value={item.description} onChange={(e) => updateItem(index, 'description', e.target.value)} /></Field><Field label="Quantity" required><input className={input} type="number" min="0.01" step="0.01" value={item.quantity} onChange={(e) => updateItem(index, 'quantity', e.target.value)} /></Field><Field label="Unit" required><input className={input} value={item.unit} onChange={(e) => updateItem(index, 'unit', e.target.value)} placeholder="bag, kg" /></Field><Field label="Unit price" required><input className={input} type="number" min="0.01" step="0.01" value={item.unitPrice} onChange={(e) => updateItem(index, 'unitPrice', e.target.value)} /></Field><div className="flex items-end gap-2"><div className="min-h-11 flex-1 rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold text-slate-800">{money((Number(item.quantity) || 0) * (Number(item.unitPrice) || 0))}</div><button type="button" onClick={() => removeItem(index)} className="min-h-11 rounded-xl p-3 text-red-600 hover:bg-red-50" aria-label="Remove item"><Trash2 className="h-4 w-4" /></button></div></div></div>)}</div><div className="flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={addItem} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-green-700 px-4 py-2 font-semibold text-green-700 hover:bg-green-50"><Plus className="h-4 w-4" /> Add farm input</button><p className="text-lg font-bold text-slate-900">Grand total: {money(inKindTotal)}</p></div></>}</div>}
      {step === 5 && <div className="space-y-4"><div><h3 className="font-bold text-slate-900">Co-maker information</h3><p className="text-sm text-slate-500">Complete all fields when a co-maker is required for this application.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Co-maker name"><input className={input} value={form.coMakerName} onChange={(e) => update('coMakerName', e.target.value)} /></Field><Field label="Relationship to borrower"><input className={input} value={form.coMakerRelationship} onChange={(e) => update('coMakerRelationship', e.target.value)} /></Field><Field label="Address"><input className={input} value={form.coMakerAddress} onChange={(e) => update('coMakerAddress', e.target.value)} /></Field><Field label="Contact number"><input className={input} value={form.coMakerContact} onChange={(e) => update('coMakerContact', e.target.value)} /></Field></div></div>}
      {step === 6 && <div className="space-y-4"><div><h3 className="font-bold text-slate-900">Collateral information</h3><p className="text-sm text-slate-500">Provide both fields whenever collateral applies.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Collateral type"><select className={input} value={form.collateralType} onChange={(e) => update('collateralType', e.target.value)}><option value="">No collateral entered</option><option>Land Title / Property</option><option>Harvest</option><option>Savings Deposit / Share Capital</option></select></Field><Field label="Collateral description / details"><textarea className={input} rows={3} value={form.collateralDetails} onChange={(e) => update('collateralDetails', e.target.value)} /></Field></div></div>}
      {step === 7 && <div className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><h3 className="font-bold text-slate-900">Review your application</h3><p className="mt-1 text-sm text-slate-600">Use Back to correct anything before submitting. Financial totals below are estimates and are recalculated by the server.</p><div className="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><div><p className="text-slate-500">Member / borrower</p><p className="font-semibold">{selectedMember?.memberId} · {selectedMember?.name}</p></div><div><p className="text-slate-500">Farm</p><p className="font-semibold">{area.toFixed(2)} ha · {form.cropsPlanted}</p></div><div><p className="text-slate-500">Loan</p><p className="font-semibold capitalize">{form.loanType} · {form.loanMode}</p></div><div><p className="text-slate-500">Purpose</p><p className="font-semibold">{form.purpose}</p></div><div><p className="text-slate-500">Co-maker</p><p className="font-semibold">{form.coMakerName || 'Not provided'}</p></div><div><p className="text-slate-500">Collateral</p><p className="font-semibold">{form.collateralType || 'Not provided'}</p></div></div></div>{calculationPanel}{confirming && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="font-semibold text-amber-900">Confirm final submission?</p><p className="mt-1 text-sm text-amber-800">The application will be sent for administrative review and duplicate pending applications are blocked.</p><div className="mt-3 flex gap-2"><button type="button" disabled={saving} onClick={submit} className="min-h-11 rounded-xl bg-green-700 px-4 py-2 font-semibold text-white hover:bg-green-800 disabled:opacity-60">{saving ? 'Submitting…' : 'Confirm and submit'}</button><button type="button" disabled={saving} onClick={() => setConfirming(false)} className="min-h-11 rounded-xl bg-white px-4 py-2 font-semibold text-slate-700 ring-1 ring-slate-200">Cancel</button></div></div>}</div>}
    </div></div><div className="flex flex-col-reverse gap-3 border-t border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><button type="button" onClick={step === 1 ? onCancel : () => { setError(''); setStep((current) => current - 1); }} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 py-2 font-semibold text-slate-700 hover:bg-slate-200"><ChevronLeft className="h-4 w-4" /> {step === 1 ? 'Cancel' : 'Back'}</button>{step < 7 ? <button type="button" onClick={next} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-green-700 px-4 py-2 font-semibold text-white hover:bg-green-800">Next <ChevronRight className="h-4 w-4" /></button> : <button type="button" onClick={() => setConfirming(true)} className="min-h-11 rounded-xl bg-green-700 px-4 py-2 font-semibold text-white hover:bg-green-800">{submitLabel}</button>}</div></div>;
}
